[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "forge-std/=lib/forge-std/src/",
  "contracts/=../contracts/",
  "interfaces/=../interfaces/",
  "utils/=../utils/",
  "local/=src/"
]

allow_paths = ["../contracts", "../interfaces", "../utils"]
